vms:
  hosts: 
    ubuntu20-vm1:
      ansible_host: 192.168.42.101
      ansible_ssh_pass: sachi 
      ansible_ssh_user: sachi
      ansible_sudo_pass: sachi
    ubuntu20-vm2:
      ansible_host: 192.168.42.195
      ansible_ssh_pass: sachi 
      ansible_ssh_user: sachi
      ansible_sudo_pass: sachi
      